### ISSUE TITLE
Error connecting controller

### ISSUE THREAD

**Issue by snake117** [excid3/noticed#10]
I have not implemented any notifications yet. I just included the 'noticed' gem in my application (note: I am using JumpStart Pro and merged the update).

In my console, I receive this error on every page:
![Screenshot 2020-08-04 10 17 07](https://user-images.githubusercontent.com/6279194/89304957-0ba58480-d63c-11ea-9b65-cd8f0469b677.png)

I'm not sure if there is something wrong with my project setup only or if other users could encounter this same issue.

How can we go about fixing this?

Thanks!

**Comment by excid3** [comment]
I just pushed a fix for that literally 30 seconds ago to the Jumpstart Pro repo. We must be on the same wavelength. 😎

If it's Javascript related, you can post an issue on the Jumpstart Pro GitLab issues, since this gem doesn't come with any of that.

**Comment by snake117** [comment]
Wow, talk about fast XD

Thank you :)
