### ISSUE TITLE
include Noticed::Model in model but it runs forever in rspec testing

### ISSUE THREAD

**Issue by ngoc-daisy** [excid3/noticed#100]
I use `Noticed` gem to send message into email by notification. In the photo, you can see my model (**SystemNotification**). I include Noticed::Model module to use many method in this module. However, rspec test file runs forever. I realize it has the problem when I create a notification (**:notification**). I checked it by `byebug` so I make sure. I use wrongly ? Can you help me, please ? Thank you. 🙂 
<img width="312" alt="Screen Shot 2021-03-19 at 5 38 15 PM" src="https://user-images.githubusercontent.com/80373024/111769831-3d720f80-88dc-11eb-8f57-8c01f376d61b.png">
<img width="873" alt="Screen Shot 2021-03-19 at 5 49 48 PM" src="https://user-images.githubusercontent.com/80373024/111769853-44008700-88dc-11eb-8f50-d442bd6674f2.png">
<img width="958" alt="Screen Shot 2021-03-19 at 5 57 17 PM" src="https://user-images.githubusercontent.com/80373024/111770143-9f327980-88dc-11eb-8e02-4af01bf12041.png">

**Comment by ngoc-daisy** [comment]
Can anyone help me, please ? 😄

**Comment by excid3** [comment]
Try to simplify your code so you can figure out what method is hanging.
