### ISSUE TITLE
NameError: Unitialized constant CommentNotification

### ISSUE THREAD

**Issue by bellemscott** [excid3/noticed#111]
I am following along with the tutorial, and the CommentNotification object gets created fine, I verified that the file comment_notification.rb is under the notifications directory, but when I try run the line in rails c `notif = CommentNotification.with(post: 1)` , it says it doesn't know what CommentNotification refers to (AKA name error described above). Gem version is 1.3.2. Not sure what to do here, I followed the tutorial step for step.

**Comment by excid3** [comment]
Hey @bellemscott! That's a good question. 

Maybe try `spring stop` in your terminal and then run `rails c` and see if it can find `CommentNotification` ?

**Comment by bellemscott** [comment]
That did it, thanks!
