### ISSUE TITLE
Best practices for testing notifications

### ISSUE THREAD

**Issue by dwightwatson** [excid3/noticed#114]
I'm working on replacing some mailers and other custom delivery classes with notifications, and I'm wondering what the best approach to testing them might be. I guess there are two considerations: 

* Testing that a notification is scheduled for delivery (through a controller request test)
* Testing the deliveries that a notification makes (under a unit test?)

I can't seem to find if they exist already, but if not it seems like it would be a great addition. Has anyone been testing notifications already, and how so?

I wonder if there's an opportunity for helper methods in testing much like [ActiveJob](https://api.rubyonrails.org/classes/ActiveJob/TestHelper.html#method-i-assert_enqueued_jobs)/[ActiveMailer](https://api.rubyonrails.org/v6.1.0/classes/ActionMailer/TestHelper.html) - standalone assertions, or blocks. 

```rb
expect {
  post comments_path, params: {comment: attributes_for(:comment)}
}. to have_enqueued_notification(NewComment, User.all)
```

Alternatively some type of fake notification driver might open up more expressive notification test opportunities, similar to Laravel, like:

```rb
NewComment.assert_sent_to(User.first)

Notification.assert_sent_to(NewComment, User.first)

Notification.assert_nothing_sent
```

This is all just spitballing - I'm not even sure how to provide test helpers, or how difficult it is to support Minitest and RSpec. However ease of testability would feel right at home alongside Rails.

**Comment by excid3** [comment]
I've just been doing your typical ActiveJob tests for enqueuing notifications:

```ruby
  test "asserts delivery is delayed" do
    freeze_time do
      assert_enqueued_with(at: 5.minutes.from_now) do
        With5MinutesDelay.new.deliver(user)
      end
    end
  end
  ```
  
Each delivery method is an ActiveJob, so you can use it as the `job: Noticed::DeliveryMethods::Email` argument, or leave it out if you don't care.

We do have a Test delivery method that you can use as well: https://github.com/excid3/noticed/blob/master/lib/noticed/delivery_methods/test.rb

**Comment by dwightwatson** [comment]
Cool, thanks for that, really helpful!

**Comment by christopheragnus** [comment]
Hey - what's the recommended way to test notifications with Twilio, etc & using Rspec?

**Comment by excid3** [comment]
@christopheragnus just stub out the HTTP request. You can do that a bunch of different ways. 

Easiest is to just stub the `post` method on the delivery method with: https://relishapp.com/rspec/rspec-mocks/v/2-99/docs/method-stubs

You can also stub the request if you want to use Webmock / VCR.
