### ISSUE TITLE
Dynamic Credentials

### ISSUE THREAD

**Issue by berniechiu** [excid3/noticed#116]
Hi Chris, Thanks for this nice little gem.

I wonder if I want to allow clients to use their own credentials (of course will be encrypted too, probably using `attr_encrypted`), is it possible to dynamically switch credentials instead of globally set up in `Rails.application.credentials`? Thanks!

**Comment by excid3** [comment]
Already supported. 👍 

See the `credentials` option for the various delivery methods. For example with Twilio: https://github.com/excid3/noticed#options-5

**Comment by berniechiu** [comment]
Thanks
