### ISSUE TITLE
unable to broadcast to action cable when using string

### ISSUE THREAD

**Issue by jose2007kj** [excid3/noticed#141]
`NoMethodError (undefined method `notifications' for "user_channel_1":String)`

this line is giving me above  error `LeaveRequestNotification.with(req: self).deliver( "user_channel_#{@receiver[:id]}")`

but it works fine when i give LeaveRequestNotification.with(req: self).deliver( @receiver)

My goal is to deliver notification to a specific user by id. Is this supported? please guide me

Thanks

**Comment by excid3** [comment]
You have to pass an ActiveRecord object to `deliver()`

**Comment by jose2007kj** [comment]
thanks, 
how shall i pass a string as channel name, i want to broadcast to "user_channel_1"

**Comment by excid3** [comment]
You wouldn't. You'd set the option for `channel` on your Notification. https://github.com/excid3/noticed#actioncable

**Comment by jose2007kj** [comment]
```
class LeaveRequestNotification < Noticed::Base
  deliver_by :database#, format: :to_database
  deliver_by :action_cable, channel: 'UserChannel'
end

class UserChannel < ApplicationCable::Channel
  def subscribed
    stream_for "user_channel_#{params[:id]}"
  end

  def unsubscribed
    # Any cleanup needed when channel is unsubscribed
  end
end

```
sorry of not being clear
currently its broadcasting to `user:Z2lkOi8vamFuZC1yLWJhY2tlbmQvVXNlci8x` but i want it to broadcast to "user_channel_#{@received[:id]}"

for project comment notification i was previously sending like the following

`ActionCable.server.broadcast("project_comment_#{self.project_id}", {"id":self.id, "user": self.user.name, "comment":self.comment, "created_at": self.created_at,'project_d': self.project_id})
  `
  
 thanks

**Comment by excid3** [comment]
You may need to create your own delivery method for that. The ActionCable one will always `broadcast_to recipient`.

**Comment by jose2007kj** [comment]
ok, i just wanted it to deliver to recipent, but i thought `user:Z2lkOi8vamFuZC1yLWJhY2tlbmQvVXNlci8x` is common for all users
thanks

**Comment by excid3** [comment]
That's a unique ID for each user from `stream_for user` using the NotificationChannel that comes with the gem:

https://github.com/excid3/noticed/blob/master/lib/noticed/notification_channel.rb#L4

That way you can broadcast notifications to individual users as long as the client side ActionCable connects to that channel. 👍

**Comment by excid3** [comment]
We can probably add another option for the ActionCable delivery method to allow you to override the `broadcast_to` and pass a custom channel name / object though. That would make using different channels easier.

**Comment by jose2007kj** [comment]
Thanks a lot again for explaining everything in details
have a nice day

**Comment by excid3** [comment]
Want to try this branch? I haven't tested it yet. 

https://github.com/excid3/noticed/compare/action-cable-option?expand=1

This would let you pass in a `stream` option which would be like your example above:

```ruby
deliver_by :action_cable, channel: MyChannel, stream: :custom_stream

def custom_stream
  "user_#{recipient.id}"
end
```
