### ISSUE TITLE
Twilio issues - need to use form data instead of json?

### ISSUE THREAD

**Issue by patmisch** [excid3/noticed#16]
I could not for the life of me get Twilio notifications to send. I finally cloned `noticed` and poked around a bit. I found that Twilio was returning `{"code": 21602, "message": "Message body is required."}`

Changing the `HTTP` post call to use `form` instead of `json` fixed it. I have a pull request ready, but I'm wondering if there is something else going on here? I'd have to imagine this was tested at some point... is there something else I may have been doing wrong?

**Comment by excid3** [comment]
That makes sense! I actually haven't fully tested out Slack, Twilio, or Vonage as I was primarily working on the core. I sketched out those and intended to link up my API keys to test them and totally forgot to.

Appreciate the PR for that!

**Comment by patmisch** [comment]
Fixed with Pull Request #17
