### ISSUE TITLE
iOS delivery support certificate based auth method

### ISSUE THREAD

**Issue by erbunao** [excid3/noticed#184]
At the moment, the only way to connect with Apnotic is via a token-based connection.

```
# lib/noticed/delivery_methods/ios.rb

  def connection_pool_options
    {
      auth_method: :token,
      cert_path: cert_path,
      key_id: key_id,
      team_id: team_id
    }
  end

```

While this is a great start and would cover most cases, I think it would be great to have some parity with Apnotic's options. That is to have an option to choose between certificate-based vs token-based authentication.

Reference: https://github.com/ostinelli/apnotic/blob/d7e76897fb52b4bd026b9a6aa87f359872b78540/README.md#objects

**Comment by excid3** [comment]
We didn't really want to encourage certificate authentication because it requires you to renew that cert yearly which makes it more of a pain to manage. Token auth doesn't have that restriction which is really nice.

That said, I'd be happy to accept a PR to support it.

**Comment by erbunao** [comment]
That is very true and I would use token based authentication for most cases as well. 

One thing I found out, and I might be missing something, about this mechanism is it could be very easy to point a push notification from non-production app to a production app by simply updating the bundle_identifier. This could be out of scope of the mechanism itself but with a certificate, this could be avoided. 

Nonetheless, I'm still sticking with token based mechanism as the yearly cert management is cumbersome. But I would love to open up the other auth option just in case it is needed.

**Comment by joemasilotti** [comment]
If you make sure to set the development flag in noticed it will use the sandbox APNS server. Then it will fail to send a notification from a dev token to a prod app.

**Comment by erbunao** [comment]
@joemasilotti thanks for the suggestion! That makes complete sense. I think if the development app is installed via Xcode, that would be safer since push notifications won't be accidentally sent to production apps.

In our current setup though, our test and staging apps are installed via TestFlight so the `development` flag shouldn't be set in order for Apple to send a push notification. This is my understanding from Apnotic's [docs](https://github.com/ostinelli/apnotic#objects).

> The concepts of PRODUCTION and DEVELOPMENT are different from what they used to be in previous specifications. Anything built directly from Xcode and loaded on your phone will have the app generate DEVELOPMENT tokens, while everything else (TestFlight, Apple Store, HockeyApp, ...) will be considered as PRODUCTION environment.

I guess a setup like this would need more safe-guarding checks to minimize the accidents. I would love to learn though how other teams approach testing in different environments.

**Comment by joemasilotti** [comment]
That's correct. 

I add the bundle identifier to the environment-specific credentials. Then staging can point to TestFlight only, if needed. 

Another approach is to persist the bundle identifier and/environment with the token in the database. Then you have full control to match them up correctly per environment.
