### ISSUE TITLE
Noticed gem does database check during assets:precompile

### ISSUE THREAD

**Issue by wflanagan** [excid3/noticed#197]
I'm working on cleaning up my deployment using Docker.

In my CI, I am trying to build an image. Ideally, this image should be able to be built (asset compilation) without connecting to a live database.  

But, this gem seems to require a valid, live connection when my app is booting to do asset:precompile. I can't stub it out like I can with others for a dummy url. It checks the health of the connection, and throws an error.  

For now, I'm instrumenting an entire database in asset compilation for this. But, it would be nicer to not have to do so. 

I'm using the approach roughly outlined in this gemfile for making small images, FYI. 
https://github.com/ledermann/docker-rails-base/blob/main/Builder/Dockerfile

**Comment by excid3** [comment]
You can just change the migration to set the column type hard coded instead of dynamically.

In fact, we can probably update the generator so it does the same.
