### ISSUE TITLE
Multi tenant not working

### ISSUE THREAD

**Issue by AlkhabazHasan** [excid3/noticed#204]
I'm using act as tenant gem, and I followed Chris Oliver tutorial on YouTube.
but I got this error, when I use act as tenant:
`uninitialized constant PropertyNotification::Current `

Notifications model:
  belongs_to :account
  acts_as_tenant :account

In `PropertyNotification < Noticed::Base`
```
def to_database
    {
      type: self.class.name,
      params: params,
      account: Current.account
    }
end
```

**Comment by excid3** [comment]
You might want `::Current.account` to look for a top-level constant.
