### ISSUE TITLE
Generate notification classes inside `models` folder

### ISSUE THREAD

**Issue by danilobarion1986** [excid3/noticed#24]
When following the setup instructions, when we ran `rails generate noticed:notification CommentNotification`, the generated class is put on the `app/notifications/comment_notification.rb` file. 

That way, rails doesn't find the created class. 

Maybe is better to create new classes in `app/models/notifications/comment_notification.rb` as the default location. If so, the generator should also add the correct namespace to the class name. Or we could add the app/notifications on the loaded paths array, but I think that is more intrusive.

**Comment by excid3** [comment]
Rails will automatically load files in any folder under `app` so there's no need to change that. Works just fine in our test dummy app and Jumpstart and every other app I've tested with.

If I had to guess, maybe your app has changed how the Rails autoloader works?

**Comment by danilobarion1986** [comment]
Thanks for the reply! Yet I didn't change the autoloader, I got that weird behavior when testing from the rails console. But I just tested it again, and it works like you said!

**Comment by excid3** [comment]
Hah! Wonder why that was. Maybe spring?

**Comment by danilobarion1986** [comment]
Dunno, it was a nearly fresh rails 6 demo project to test things out... Happy that it worked one day after, though! 😅  Thanks!
