### ISSUE TITLE
Can't seem to query for params

### ISSUE THREAD

**Issue by reinvanimschoot** [excid3/noticed#241]
I'm trying to to do something similar to https://github.com/excid3/noticed/issues/122, that is, querying for for a specific param:

```rb
current_user.notifications.where('params @> ?', { discussion: { id: 1 } }.to_json)
```
I also added `has_noticed_notifications` to the `discussion` model.

But I'm not getting any results. I tried using `.to_json` and I tried without but without, I'm getting a ruby error.

Am I overlooking something?

**Comment by ykamin-booth** [comment]
I've also been having issues querying for params.

```
class User < ApplicationRecord
 has_many :notifications, as: :recipient
end
```
```
class Message < ApplicationRecord
 has_noticed_notifications
end
```

`EventMessageNotification.with(message: message, event: event).deliver_later(recipients)`

When i query
`message.notifications_as_message.where(recipient: user)`
I'm finding the notification. But when I query
`user.notifications.where('params @> ?', {message: {id: message.id}}.to_json)`
or
`user.notifications.where(params: {message: message})`
or
`user.notifications.where(params: {message: {id: message.id}})`
I'm not finding the notification

**Comment by ykamin-booth** [comment]
It does work when I just replicate the notifications_as_#{param_name} method in my code:

`user.notifications.where("params @> ?", Noticed::Coder.dump(:message => message).to_json)`

**Comment by excid3** [comment]
Rails converts the param object into a special hash to encode/decoded Ruby objects. You can see how we query those 
here: https://github.com/excid3/noticed/blob/master/lib/noticed/has_notifications.rb#L17

Alternatively, just pass `discussion_id: 1` to params and you can skip the object coder.
