### ISSUE TITLE
Segmentation fault at after adding/installing noticed and 

### ISSUE THREAD

**Issue by Bishwas-py** [excid3/noticed#244]
Rails app's not working after the installation of noticed. None of the rails command is working...

```
<internal:trace_point>:346: [BUG] Segmentation fault at 0x0000000000000008
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

-- Control frame information -----------------------------------------------
c:0050 p:0003 s:0295 e:000294 METHOD <internal:trace_point>:346
c:0049 p:0016 s:0291 e:000289 BLOCK  /var/lib/gems/2.7.0/gems/debug-1.6.1/lib/debug/sessi
```

**Comment by Bishwas-py** [comment]
My rails version is `Rails 7.0.3.1`

**Comment by apurv-1** [comment]
I think you need to do db migration, try running

`bin/rails db:migrate:status`

if you see any migration status down, run `bin/rails db:migrate` then, restart the server.

**Comment by excid3** [comment]
This isn't related to Noticed.  Looks like an issue with your Ruby installation.
