### ISSUE TITLE
wrong number of arguments (given 0, expected 1) on mailers

### ISSUE THREAD

**Issue by LimeBlast** [excid3/noticed#25]
Can you show an example mailer that works with this, please? I'm unable to get it working correctly as I'm getting the error

```
wrong number of arguments (given 0, expected 1)
/app/app/mailers/engineer_mailer.rb:48:in `timesheet_reminder'
```

My mailer looks like this:

```
class EngineerMailer < ApplicationMailer
  def timesheet_reminder(recipient)
    timesheet = Timesheet.new(
      date: Date.current.beginning_of_week,
      account: recipient
    )

    @timesheet_title = timesheet.to_label
    @timesheet_url = engineers_timesheet_url(timesheet.slug)
    mail to: timesheet.account.email
  end
end
```

And I'm guessing the missing arguments relates to the `recipient` I want to pass in.

My notification looks like this:

```
class EngineerTimesheetReminderNotification < BaseNotification
  deliver_by :database
  deliver_by :email,
             mailer: "EngineerMailer",
             method: "timesheet_reminder"

  deliver_by :twilio,
             credentials: :get_twilio_credentials

  param :engineer

  def url
    timesheet = Timesheet.new(
      date: Date.current.beginning_of_week,
      account: engineer
    )

    engineers_timesheet_url(timesheet.slug)
  end
end
```

What am I missing? Thanks.

**Comment by LimeBlast** [comment]
Never mind, I figured it out. Apparently ActionMailer has changed since I last looked, and uses the new `.with` syntax to assign parameters.

With this in mind, I was able to change the mailer to the following, and it worked:

```
class EngineerMailer < ApplicationMailer
  def timesheet_reminder
    timesheet = Timesheet.new(
      date: Date.current.beginning_of_week,
      account: params[:recipient]
    )

    @timesheet_title = timesheet.to_label
    @timesheet_url = engineers_timesheet_url(timesheet.slug)
    mail to: timesheet.account.email
  end
end
```

**Comment by etewiah** [comment]
Hey @LimeBlast , funny to see you here (This is Ed from brum.io ;)

Would love a link to the documentation for the "with" syntax.  I'm not very familiar with that keyword and its not very google friendly unfortunately :(

**Comment by etewiah** [comment]
Ah, never mind.  Found it here:

https://api.rubyonrails.org/classes/ActionMailer/Parameterized/ClassMethods.html#method-i-with

**Comment by excid3** [comment]
Yeah! It's not very easy to find. Glad you found the parameterized mailers. It's a nice improvement they made a few years ago and saves you from having to set instance variables all the time.

**Comment by etewiah** [comment]
> Yeah! It's not very easy to find. Glad you found the parameterized mailers. It's a nice improvement they made a few years ago and saves you from having to set instance variables all the time.

And I suppose its what inspired you to use the ".with" convention too.  Nice to learn these sort of little details.

Might as well take this opportunity to thank you for this awesome gem and everything else you do for the community.  I love your podcast and feel much more a part of your world than perhaps you can imagine ;)  Much love and respect from a snow-trapped Madrid!

**Comment by excid3** [comment]
That is amazing to hear. Thanks for that @etewiah! After the pandemic is over, Spain is one of the places I absolutely want to visit. 👋

**Comment by etewiah** [comment]
Make sure to give me a shout if you do make it here @excid3 .  There are good Ruby meetup groups in Madrid and Malaga and we would be delighted to have you here.  The Spanish are very hospitable and you'll find little to complain about regarding the drinking and tapas culture..

**Comment by excid3** [comment]
Will do! I watch a lot of Jon Olsson on YouTube and he's got a place in Marbella and it just looks amazing! 

Just saw on Hacker News central Spain hit -25C! That is cold!

**Comment by etewiah** [comment]
DHH has a home close to Marbella too. The local Ruby meetup group there has been trying to figure out a way of tempting him to make an appearance someday.

**Comment by rsmithlal** [comment]
> Never mind, I figured it out. Apparently ActionMailer has changed since I last looked, and uses the new `.with` syntax to assign parameters.
> 
> With this in mind, I was able to change the mailer to the following, and it worked:
> 
> ```
> class EngineerMailer < ApplicationMailer
>   def timesheet_reminder
>     timesheet = Timesheet.new(
>       date: Date.current.beginning_of_week,
>       account: params[:recipient]
>     )
> 
>     @timesheet_title = timesheet.to_label
>     @timesheet_url = engineers_timesheet_url(timesheet.slug)
>     mail to: timesheet.account.email
>   end
> end
> ```

Thank you! I was tearing my hair out trying to figure out why the keyword arguments that I had defined for my mailer action were not getting picked up. I has assumed that the kwargs would receive the values passed to the `with` method, but now I realize that they are only available inside the `params` object in the mailer action.

I removed my kwargs and used the params object to set my instance variables and now it's working.
