### ISSUE TITLE
How to handle deletion on other relation

### ISSUE THREAD

**Issue by dvodvo** [excid3/noticed#252]
The readMe provides a few mechanisms to delete associated records.
```
class Post < ApplicationRecord
  # Standard association for deleting notifications when you're the recipient
  has_many :notifications, as: :recipient, dependent: :destroy
```
However, I have a `NewPostNotification`  with  `param :post` and the relation instead is based on 
```
class User < ApplicationRecord
  has_many :notification, as: :recipient

class Post < ApplicationRecord
  has_noticed_notifications
```

which, when launching  on a Post object `@post.destroy` hits and internal error `relation "notifications" does not exist`
So, in a sense, the application knows there is a notification object associated to the post, but is unaware of the relation **based on standard rails functions**

How should one go about destroying this object?  With console `User.last.notifications` is an Object that does not support #inspect  so there is no obvious way about this.

**Comment by excid3** [comment]
The recipient is the only one you can use a `has_many` on because it's a polymorphic relationship.

Records that are in `params` like `post` are in json columns, and therefore can't use `has_many :notifications`.

**Comment by dvodvo** [comment]
So what would you suggest? 
If a User has_many :posts  that are subject to database notifications, what to do considering a potential`post.destroy`?
On the other hand, I never liked the idea of destroying objects, rather make them invisible or disabled...

**Comment by excid3** [comment]
You don't have a notifications table it says.

**Comment by dvodvo** [comment]
Ah!  Misinterpreted the error message.  `relation "notifications" does not exist` usually infers that the model does not specify the relation, yet, `has_noticed_notifications` was set.    The previous element `PG::UndefinedTable` says no table - which was the case. 

[*no idea how the migration got lost*]
