### ISSUE TITLE
Unable to get Twilio working

### ISSUE THREAD

**Issue by LimeBlast** [excid3/noticed#26]
Me again. I have no idea what  I'm doing wrong, but I'm unable to get any Twilio notifications to send. Here's my code:

```ruby
class EngineerTimesheetReminderNotification < BaseNotification
  deliver_by :database
  deliver_by :email,
             mailer: "EngineerMailer",
             method: "timesheet_reminder",
             if: :email_notifications?
  deliver_by :twilio,
             credentials: :get_twilio_credentials,
             if: :sms_notifications?

  param :engineer
end
```

```ruby
class BaseNotification < Noticed::Base
  def email_notifications?
    recipient.notification == 'email'
  end

  def sms_notifications?
    recipient.notification == 'sms'
  end

  def get_twilio_credentials
    {
      account_sid: ENV.fetch('TWILIO_ACCOUNT_SID'),
      auth_token: ENV.fetch('TWILIO_AUTH_TOKEN'),
      phone_number: ENV.fetch('TWILIO_PHONE_NUMBER')
    }
  end
end
```

```yaml
en:
  notifications:
    engineer_timesheet_reminder_notification:
      message: "Please submit your timesheet before 8am Monday morning so we can process your payment."
```

I've also implemented a `.phone_number` method on the `Account` object, and have set `notification` to `'sms'`

I'm currently testing on the rails console using:

```ruby
foxy = Account.find_by_email 'developer@foxsoft.co.uk'
EngineerTimesheetReminderNotification.with(engineer: foxy).deliver(foxy)
```

and get the following output:

```
Performing Noticed::DeliveryMethods::Database (Job ID: 2016e766-60e3-4d84-ad1c-e9b229164c20) from DelayedJob(default) enqueued at  with arguments: {:notification_class=>"EngineerTimesheetReminderNotification", :options=>{}, :params=>{:engineer=>#<GlobalID:0x000055993e488410 @uri=#<URI::GID gid://system10/Account/6>>}, :recipient=>#<GlobalID:0x000055993e49bd58 @uri=#<URI::GID gid://system10/Account/6>>, :record=>nil}
Performed Noticed::DeliveryMethods::Database (Job ID: 2016e766-60e3-4d84-ad1c-e9b229164c20) from DelayedJob(default) in 30.66ms
Performing Noticed::DeliveryMethods::Twilio (Job ID: d6d97985-c504-42be-b235-e27a560c3301) from DelayedJob(default) enqueued at  with arguments: {:notification_class=>"EngineerTimesheetReminderNotification", :options=>{:credentials=>:get_twilio_credentials, :if=>:sms_notifications?}, :params=>{:engineer=>#<GlobalID:0x000055993e65a248 @uri=#<URI::GID gid://system10/Account/6>>}, :recipient=>#<GlobalID:0x000055993e659be0 @uri=#<URI::GID gid://system10/Account/6>>, :record=>#<GlobalID:0x000055993e659528 @uri=#<URI::GID gid://system10/Notification/20>>}
Performed Noticed::DeliveryMethods::Twilio (Job ID: d6d97985-c504-42be-b235-e27a560c3301) from DelayedJob(default) in 598.72ms
=> [#<Account:0x000055993e1b5f58
  id: 6,
  <snip>
]
```

I might have a  fighting  chance of seeing  what I'm doing wrong if the output from the API call was logged somewhere, but as it is right now, it seems to be fire and forget.

**Comment by JamesRClarke** [comment]
Hey Buddy.

From taking a brief look at your code, this may not be right and I will try help the best I can.

I believe that you need to define the `message` helper method in the notification class like so: 
```
# Define helper methods to make rendering easier.
def message
  t(".message")
end
```
This, I think allows Twillio and also your views to access the path directing to `message` in your en.yml file.

In your logs is there an error coming from Twillio? If so we can try and help resolve this issue.

**Comment by LimeBlast** [comment]
Hi @JamesRClarke, thanks for your offer of help.

It's my understanding that the `message` method is optional, and that without it, it'll automatically default to what I'm using in the `en.yaml` file.

There are no errors from Twilio, which is making me think it isn't even getting to them, but because the logs don't show anything other than what I've put above, I'm unable to debug what's going on.

I've had to remove it for now because I needed to get on and implement something else for now, but if @excid3 has any input on what might be wrong, I'll take another bash at it

**Comment by excid3** [comment]
Twilio uses the params by default for the message, so if you passed in `message: "Hello"` that is what it would send.

This morning I did a live stream on YouTube updating the gem to actually raise errors when the HTTP requests fail so you can more easily debug that part. I'll push that code up shortly.

**Comment by excid3** [comment]
Just pushed up that change 7891cb3 if you want to try it from git.

**Comment by excid3** [comment]
This has since been released, don't remember what version but you can find it in the changelog. Going to close this but let me know if you need anything else

**Comment by LimeBlast** [comment]
Thank you. I've not had a chance yet to go back in and try this out, but I will as soon as I'm able.
