### ISSUE TITLE
Bubble up more email errors

### ISSUE THREAD

**Issue by juliancheal** [excid3/noticed#27]
Hi Chris,

I just noticed, that I hadn't set my email up correctly, but even with `debug: true` I wasn't getting any indication I'd done anything wrong.

This is my `development.log` (Sanitised and shortened for brevity)

```
[ActiveJob] [Noticed::DeliveryMethods::Email] [<some id>]
Performing Noticed::DeliveryMethods::Email 
(Job ID: <job id>) from Sidekiq(default) enqueued at 2020-08-13T21:50:26Z with arguments: 
{:notification_class=>"ExampleNotification", :options=>{:mailer=>"UserMailer", 
  :method=>"example_notification", :debug=>true},
  :params=>{:recipient=>#<GlobalID:<etc, etc>}
[ActiveJob] [Noticed::DeliveryMethods::Email] [<some id>]
UserMailer#example_notification: processed outbound mail in 3.9ms
```

I noticed however the job was sitting in Sidekiq. Having watched your debugging screen cast the other day, I put in a byebug above line 5 https://github.com/excid3/noticed/blob/master/lib/noticed/delivery_methods/email.rb#L5

And result!

```
(byebug) mailer.with(format).send(method.to_sym).deliver
*** ActionView::MissingTemplate
Exception: Missing template user_mailer/example_notification, application_mailer/example_notification
with {:locale=>[:en], :formats=><etc, etc>}. Searched in:
  * "app/views"
  * <other gem views>
  * "gems/actiontext-6.0.3.2/app/views"
  * "actionmailbox-6.0.3.2/app/views"
```

Now maybe I could have changed a setting on my development environment that would have shown me this I'm not sure.
Anyway, just posting it here for future issue spotters.

It's a bit late in the night here for me to try and create a PR, but would be happy to help if showing this error in Noticed would be useful.

Big thank you for this library 💕

_Update:_ I realised we're using MJML for our email templates, and I had the wrong ending for my file, `html.erb` and not `.mjml` so once I fixed that, I was getting more debug messages in the logs without `byebug`.

However one more issue, and this again be related to `mjml` is that I am unable to send emails with `deliver_later`, but `deliver_now` works fine. 🤷🏼‍♀️ Anyway, it's definitely too late at night now. Happy to help out where I can anyway.

**Comment by excid3** [comment]
We just added the `debug: true` option and didn't use it in anything but API calls so far, so adding this for emails would be great.

Since things are run in background jobs, it does make debugging a bit harder. One of those being you have to make sure your background workers are running.

On a semi-related note... we need to make the background job queue and settings configurable too.

If you have any ideas on good ways we can add some more debugging info for emails and things, let me know. 👍

**Comment by juliancheal** [comment]
> We just added the `debug: true` option and didn't use it in anything but API calls so far, so adding this for emails would be great.

Ah yeah, I should have known that from watching the stream!

I'll close this issue, and try and create a PR.
