### ISSUE TITLE
`has_noticed_notifications`

### ISSUE THREAD

**Issue by jon-sully** [excid3/noticed#274]
Greetings Noticed team! Just wanted to ask a question about `has_noticed_notifications`. I love that the library ships with this association pre-canned out of the box so none of us have to figure out the sql required to make it happen ourselves, but I wanted to make sure I have the concept right. It's named `has_noticed_notifications`, which is exactly how I think of the _other_ association, `has_many :notifications` — typically used on a `User` record. So this method is called `has_noticed_notifications` but is totally _not_ the same as `has_many :notifications`, right? I'm gathering that this is an association for gathering all of the notifications in the system where this record is the _subject_ (or at least in the `params` under a specified key). E.g. that where `User` might have `has_many :notifications`, `Book` may use `has_noticed_notifications` in case we ever need to find all notifications sent to `User` records where Book #81 (for example) is in the _params_? Is that right? (and the relationship would actually be implemented as `@book.notifications_as_xyz` on `Book` if I'm reading the code right) 

Just wanting to make sure I have the idea straight! Thanks!

**Comment by excid3** [comment]
It's the same thing, but using a json column for the association instead of a regular _id.

**Comment by jon-sully** [comment]
Ah, I see. Interesting. Thanks for the clarification! I was reading it a little backwards

**Comment by jon-sully** [comment]
> It's the same thing, but using a json column for the association instead of a regular _id.

Circling back, I think that's the part that tripped me up in March.

`has_many :notifications` is the relationship for models who _receive_ notifications (Users, probably)

`has_noticed_notifications` is the relationship for "acts as notification subject" — a relationship that can give you all the notifications referencing that object instance in their params.

`has_noticed_notifications` would _not_ give you notifications where that object is the _target_ of the notification (who it's delivered to)

Just comes down to naming, but wanted to post back in case it'd help others 👍
