### ISSUE TITLE
How to handle Notifications that have had a param deleted

### ISSUE THREAD

**Issue by kylekeesling** [excid3/noticed#28]
I've ran into a problem that I'm hoping we can brainstorm on.

I have a `Comment::PostedNotifcation` that is created anytime someone posts a comment, and it looks something like this:

```
class Comment::PostedNotification < Noticed::Base
  deliver_by :database
  deliver_by :email, mailer: "CommentMailer", method: "posted"

  param :comment

  def message
    "new comment"
  end

  def url
    params[:comment].commentable_path
  end
end
```

It works great most of the time, but I allow users to delete their comments, and once that happens, and I attempt to load a user's notifications in a view I run into the following error:

` ActionView::Template::Error - Couldn't find Comment with 'id'=`

I take that to mean that while the view is re-hydrating the `Notification` record, it's attempting to look up the now-deleted comment via its SGID, but it's no longer there, and 💥 goes the dynamite.

I've begun to dig into the code and from the looks of it the `ActiveJob::Arguments` [deserializier](https://github.com/rails/rails/blob/b738f1930f3c82f51741ef7241c1fee691d7deb2/activejob/lib/active_job/arguments.rb#L41) is the point of contention, but I'm not sure where to go beyond that.

My first thought was to add a `after_destroy` callback to my `Comment` model to go back and destroy the related Notification records, but I'm not sure the best way to query based upon the serialized `params` field.

Can you think of anyway to address this problem? Happy to help with the solution if we can come up with one.

**Comment by excid3** [comment]
Yeah, if you deleted the Comment and try to rehydrate the notification for that comment, it would not be able to find the record.

There are a couple solutions to this:

1. Override the database `format` and include the comment in the database attributes that are written. You'd need to add an association to the notification model to do that. I'd recommend a polymorphic association.

2. If you change the notifications table migration to use a json(b) column, that's easily queryable so you could do the same as #1. 

We generate a text column by default for SQLite compatibility, but I'd like to make the generator smarter so we can use json by default and only use text when we have to.

**Comment by kylekeesling** [comment]
For my purposes I think it makes sense to create another polymorphic association to relate the notification to. Most of the time my notifications are in reference to one particular model/object and having a definitive place to define that seems to make the most sense for me.

Thanks for talking this through with me!

**Comment by excid3** [comment]
Readme is updated for querying the JSON columns and included instructions for the polymorphic association as well.
