### ISSUE TITLE
Reconsider unicode as default type for Vonage

### ISSUE THREAD

**Issue by dwightwatson** [excid3/noticed#280]
I noticed that [by default the Vonage driver sets the format to `unicode`](https://github.com/excid3/noticed/blob/master/lib/noticed/delivery_methods/vonage.rb#L26). While this may seem like an obvious default over `text` it's actually not.

* [`text` is the default setting on Vonage if not provided in the request](https://developer.vonage.com/en/api/sms#send-an-sms-req-body)
* using Unicode restricts the [length of a message to 70 characters instead of the usage 160 characters](https://developer.vonage.com/en/messaging/sms/code-snippets/send-an-sms-with-unicode)

I discovered this in my application because messages with URLs to users were being split across 3 messages (costing me 3x). I don't think it breaks the messages (I presume iOS/Android are smart enough to smoosh the messages back into one) as I haven't heard of this issue from customers.

Unicode would make sense when explicitly required or for non-English languages. I think it might make sense for the default to remain `text` and let developers opt-in specifically to `unicode` when they need it, especially in light of the cost savings involved.

Will submit a PR if you're happy with the change.

**Comment by excid3** [comment]
We would accept a PR that allows you to override the default. We should keep the default as unicode for now.

**Comment by dwightwatson** [comment]
I think it's easy enough to override - you just need to implement `format` and provide an alternative type in the hash (which is what I'm doing now). My concern is that it could bite developers who presume they'd have 160 characters/notification out of the box. I'll leave it for now.
