### ISSUE TITLE
Issues with GoodJob and ActionMailer::Parameterized

### ISSUE THREAD

**Issue by RailsCod3rFuture** [excid3/noticed#282]
When I fire off the notification for email -- GoodJob comes back complaining about a method being missing on the Mailer object. I don't know if this has been fixed in a later version of noticed. But I can't quite put my finger on where the problem is coming from

`[ActiveJob] [Noticed::DeliveryMethods::Email] [53d92cb5-747e-4939-b4e1-1ef03594711c] Error performing Noticed::DeliveryMethods::Email (Job ID: 53d92cb5-747e-4939-b4e1-1ef03594711c) from GoodJob(default) in 92.31ms: NoMethodError (undefined method `report_notification' for #<ActionMailer::Parameterized::Mailer:0x000000011b536d28 @mailer=ReportNotificationMailer, @params={:report=>#<Report id: 2`

**Comment by excid3** [comment]
Sounds like you haven't implemented the method on your mailer. You should do that.

**Comment by RailsCod3rFuture** [comment]
Oh, okay -- I used the default `ReportNotification.with(report: self).deliver_later(self.user)`
I'll add the method shortly -- Thanks
