### ISSUE TITLE
can we make url option dynamic for existing defined delivery method 

### ISSUE THREAD

**Issue by snawar92** [excid3/noticed#295]
hi @excid3 
can we make url option dynamic for existing defined delivery method  i can see a condition in 
https://github.com/excid3/noticed/blob/master/lib/noticed/delivery_methods/slack.rb
-->         if (method = options[:url])

class CommentNotification < Noticed::Base
  deliver_by :slack, url: :fetch_url_from_user_table_row

  def fetch_url_from_user_table_row
    User.first.slack_url
  end
end

is it also possible i can pass user_id and then use that user_id in above fetch_url_from_user_table_row

eg:

class CommentNotification < Noticed::Base
option: user_id
  deliver_by :slack, url: :fetch_url_from_user_table_row

  def fetch_url_from_user_table_row
    User.find(option[:user_id]).slack_url
  end
end

**Comment by excid3** [comment]
It already is: https://github.com/excid3/noticed/blob/master/lib/noticed/delivery_methods/slack.rb#L20

**Comment by snawar92** [comment]
is this possible ? 

class CommentNotification < Noticed::Base
option: user_id
deliver_by :slack, url: :fetch_url_from_user_table_row

def fetch_url_from_user_table_row
User.find(option[:user_id]).slack_url
end
end

**Comment by snawar92** [comment]
> is this possible ?
> 
> class CommentNotification < Noticed::Base option: user_id deliver_by :slack, url: :fetch_url_from_user_table_row
> 
> def fetch_url_from_user_table_row User.find(option[:user_id]).slack_url end end

**Comment by snawar92** [comment]
> is this possible ?
> 
> class CommentNotification < Noticed::Base option: user_id deliver_by :slack, url: :fetch_url_from_user_table_row
> 
> def fetch_url_from_user_table_row User.find(option[:user_id]).slack_url end end

@excid3

**Comment by excid3** [comment]
Yep
