### ISSUE TITLE
Unable to pass arguments to email methods

### ISSUE THREAD

**Issue by tomrossi7** [excid3/noticed#299]
I'm not sure if this follows the opinion of Noticed, but some mailer methods accept both params and arguments. I believe the current `email_format` method only really sets the params. So for example, Noticed can't send an email notification to a mailer method like this:

`UserMailer.with({ recipient: User.first }).new_comment(comment)`

Is this something Noticed should support? If so, I can take a crack at a PR.

**Comment by excid3** [comment]
I'm not sure. How do you envision the user defining those it in their Notification object?

**Comment by tomrossi7** [comment]
I set up my own custom delivery method and this is how I specified the params and args. I kinda like `email_params` better than `email_format` since its more explicit.

```
  def email_args
    params[:comment]
  end

  def email_params
    { recipient: params[:recipient]}
  end
```

**Comment by tomrossi7** [comment]
You bet! Thanks @excid3 for putting this code together!
