### ISSUE TITLE
trouble reading from `record` in custom ActionCable formatter

### ISSUE THREAD

**Issue by rjwalters** [excid3/noticed#349]
I am having a trouble reading data from the record within the ActionCable delivery. 

``` ruby

class NotificationBase < Noticed::Base
  deliver_by :database, format: :format_for_database
  deliver_by :action_cable, channel: NotificationChannel, format: :format_for_action_cable

  def format_for_database
    {
      type: type,
      params: params_entity_data
    }
  end

  def format_for_action_cable
    {
      id: record.id,
      type: type,
      params: params_entity_data,
      read_at: record.read_at,
      created_at: record.created_at
    }
  end

...
```

Should I expect this to work?

https://github.com/excid3/noticed/blob/a970f6831a5b5419e8253813d899142f61175fc6/lib/noticed/base.rb#L90

**Comment by cjilbert504** [comment]
@rjwalters - Yeah, you should have access to the notification record at that point as the database delivery method should run first and then populate that record attribute.

Can you share the error and any other relevant information that you're seeing? Thanks

**Comment by rjwalters** [comment]
you comment seems to have fixed the problem somehow ;)

I have no idea why I was getting nil accessing the record before but it must have been unrelated

**Comment by cjilbert504** [comment]
@rjwalters - Amazing lololol
