### ISSUE TITLE
Why is type nullable?

### ISSUE THREAD

**Issue by kapso** [excid3/noticed#36]
- Shouldn't it be `NOT NULL` ?
- And if that's the case, then the following should be this - `notification.send(method).merge(type: notification.class.name, params: notification.params)`

https://github.com/excid3/noticed/blob/master/lib/noticed/delivery_methods/database.rb#L1

Thanks for creating this gem 👍

**Comment by excid3** [comment]
Which piece should be NOT NULL? Not sure I'm following.

**Comment by kapso** [comment]
I mean the `type` column in `Notification` model

**Comment by excid3** [comment]
I think I just overlooked it. Seems like that would be wise to add. 👍

You want to send a PR? Or I can take care of it if you're busy.

**Comment by excid3** [comment]
The Rails model generator does not actually support specifying `null: false` https://guides.rubyonrails.org/active_record_migrations.html#column-modifiers

Since we delegate to that, there's no way to set it. 

I think I have a solution that will work by just gsubbing the file.
