### ISSUE TITLE
V2 Delivery Method Config Options Presence Validation?

### ISSUE THREAD

**Issue by jon-sully** [excid3/noticed#364]
So custom delivery methods can setup `required_options` thanks to the [`RequiresOptions`](https://github.com/excid3/noticed/blob/5294cef393c0e005cf1558e5b178d1191a3bd5e4/lib/noticed/required_options.rb#L15) concern, but we've previously noted in docs that _just_ using `required_options` would cover _presence_ validations. E.g.:

```ruby
class DeliveryMethods::Email < Noticed::DeliveryMethod
  required_options :mailer

  # ...
end

class SomeNotifier < Noticed::Event
  deliver_by :email
end

# then

SomeNotifier.with(record: @foo).deliver(@user)
#=> Noticed::ValidationError("Delivery Method `:email` requires config options: :mailer")
```

But I'm not seeing that functionality in V2 — I see that each delivery method _does_ have `:validate!` [called](https://github.com/excid3/noticed/blob/5294cef393c0e005cf1558e5b178d1191a3bd5e4/app/models/concerns/noticed/deliverable.rb#L112) but I can't find a base implementation of `validate!` for DeliveryMethod (also not in `RequiresOptions` where I think it maybe should go?). The DeliveryMethod generator template contains a stub for the `def validate!` method but it's commented out.

So.. I'm not sure if / how this even runs then (from [`deliverable.rb`](https://github.com/excid3/noticed/blob/5294cef393c0e005cf1558e5b178d1191a3bd5e4/app/models/concerns/noticed/deliverable.rb#L110)): 

```ruby
    def validate_delivery_methods!
      bulk_delivery_methods.values.each(&:validate!)
      delivery_methods.values.each(&:validate!)
    end
```

Because the Delivery Methods don't implement `validate!` 🤔. 

I generated a custom delivery method in the dummy app and am getting an error when trying to call `validate!` on a new instance of that delivery method directly.

**Comment by jon-sully** [comment]
All of the built-in delivery methods use `required_options` but don't implement their own `validate!` so I'm thinking this is still functionality we want, just not sure if it's currently wired up!

**Comment by excid3** [comment]
validation is handled in the DeliverBy class which is what stores the delivery method and sets it up with the options.

https://github.com/excid3/noticed/blob/main/app/models/noticed/deliverable/deliver_by.rb#L16-L18

Since it's not on the DeliveryMethod, there's no way to do custom validations on them. I didn't have a good use case for them other than checking if required options were passed. Do you?

**Comment by jon-sully** [comment]
Ah, darn. I read that over several times but for whatever reason thought it was validations for the params passed into a Notifier, not validations for the delivery method configs. Big derp. 

But no, I don't. Honestly I think presence validation is probably enough. That at least gives `#deliver` a guarantee that there'll be _something_ and then one could feasibly write their own Error-raising issue from within that space. 👍
