### ISSUE TITLE
Not able to get recipient in the mailer method

### ISSUE THREAD

**Issue by atif** [excid3/noticed#366]
I just installed the v2 of noticed gem. I've created a notifier to send an email notification as:

`NewFollowerNotifier.with(record: @current_user).deliver(@followee)`

I've set up `deliver_by :email` in the new_follower_notifier.rb as 

```
deliver_by :email do |config|
    config.mailer = 'FollowingMailer'
    config.method = :new_follower_email
end

```

Following this, I'm not able to get the `recipient` as part of params in the new_follower_email method. As per the documentation, it says `recipient` will be merged in the params object. I am able to get the `record` object in params though in mailer method

https://github.com/jon-sully/noticed/blob/update-readme/docs/delivery_methods/email.md

Kindly guide if I'm missing something here.

**Comment by excid3** [comment]
You are correct! Fixing shortly.
