### ISSUE TITLE
recipient id vary

### ISSUE THREAD

**Issue by leoamigood** [excid3/noticed#367]
**What version of Noticed are you using?**
v2.0.0

**What version of Rails are you using?**
v7.1.1

I am upgrading to noticed v2.0.0 and not sure how to go forward, since the table `:noticed_notifications` column `:recipient`
is expected to of certain type. In my case recipient primary id may be UUID as well as bigint and that breaks the upgrade.

Also, all examples show:
# Instantiate a new notifier
CommentNotifier.with(record: @comment, foo: "bar").**deliver_later**(User.all)

but when method `deliver_later` is just simply not available (`deliver` works just fine)

Please suggest.

**Comment by excid3** [comment]
It's exactly the same as v1, but we moved the recipient to a new model. It is simply a standard polymorphic belongs_to as it always was. You can modify the migration for whatever you need.

**Comment by leoamigood** [comment]
Sure, but in v2 i am getting this error now:
```
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "recipient_id" of relation "noticed_notifications" violates not-null constraint
```

vs in v1 i did not have to supply `record` parameter to `with` method and hence i had no issues

**Comment by excid3** [comment]
You'll have to provide details and an example case to reproduce the issue.

**Comment by leoamigood** [comment]
Sure. Here is the v1 working case:
```
    recipient = User.find(recipient_id)

    notification = InvitationNotification.with(recipient:, invitation_token:)
    notification.deliver_later(recipient)
```

```
class InvitationNotification < BaseNotification
  deliver_by :sendgrid, # i use custom delivery, but it should not matter
             class:       'DeliveryMethods::Sendgrid', 
             template_id: Settings.sendgrid.templates.user.invitation_instructions,

  param :invitation_token
end
```
```
class BaseNotification < Noticed::Base
  param :recipient
end
```
```
class CreateNotifications < ActiveRecord::Migration[7.1]
  def change
    create_table :notifications, id: :uuid do |t|
      t.references :recipient, polymorphic: true, null: false, type: :uuid
      t.string :type, null: false
      t.jsonb :params
      t.datetime :read_at

      t.timestamps
    end
    add_index :notifications, :read_at
  end
end
```

Did i miss something?

**Comment by excid3** [comment]
I confirmed it works fine with:

```ruby
    enable_extension 'pgcrypto' unless extension_enabled?('pgcrypto')
    create_table :accounts, id: :uuid, default: 'gen_random_uuid()' do |t|
      t.timestamps
    end

  create_table "noticed_notifications", force: :cascade do |t|
    t.string "type"
    t.bigint "event_id", null: false
    t.string "recipient_type", null: false
    t.uuid "recipient_id", null: false
    t.datetime "read_at", precision: nil
    t.datetime "seen_at", precision: nil
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["event_id"], name: "index_noticed_notifications_on_event_id"
    t.index ["recipient_type", "recipient_id"], name: "index_noticed_notifications_on_recipient"
  end
```

```ruby
ExampleNotifier.deliver(Account.first)
#=> #<ExampleNotifier::Notification
 id: 980190963,
 type: "ExampleNotifier::Notification",
 event_id: 980190963,
 recipient_type: "Account",
 recipient_id: "aa67c98c-d81f-5a9c-b0bc-26caa0051aea",
```

If you're not using UUID consistently for all your models (you should), then you probably want the type to be a `string` instead. You will not be able to store an integer in the uuid column.
