### ISSUE TITLE
Problem when deploying gem and ActionCable is not configured

### ISSUE THREAD

**Issue by kylekeesling** [excid3/noticed#39]
Last night I finally deployed my implementation of your gem to production 🎉

That said I ran into an issue that caused me some downtime, so I'm hoping to bringing it to your attention to see if there is any kind of safeguard/solution we can come up with to prevent this for other folks.

My app pre-dates ActionCable, and I've yet to actually use it for anything, including the integration with this gem, so I don't have anything built out in the `channels` directory.

Turns out though, that there is code in the gem ([found here](https://github.com/excid3/noticed/blob/82e2e126ba6cb570a7125161f02d4fa59f5613ff/app/channels/noticed/notification_channel.rb#L2)) that assumes that `channels/application_cable/channel.rb` exists, and since eager loading/caching is only enabled in production I didn't find that out until my code was deployed 😅

I know that this identifies a gap in my deployment/testing strategy but I'm wondering if there's a way we could have some sort of check (potentially upon the gem's installation/in one of the generators) that would make sure that all necessary files/classes exist, or is it possible that this code can be optional dependent about whether the app utilizes ActionCable?

**Comment by excid3** [comment]
Yeah, we could move that file and only require it if ActionCable exists.

You're running Rails 6.0 though right? (I believe that's a requirement in the gemspec). I would guess that the `app/channels` folder isn't in your app or doesn't contain the application_channel.rb file.

I think it's reasonable to move that file so it's only required if `ApplicationCable::Channel` is defined.

**Comment by kylekeesling** [comment]
That's correct, I'm running on Rails 6, I just didn't have a file at `app/channels/application_cable/channel.rb`.

**Comment by excid3** [comment]
Makes sense. We probably can't provide the class as part of the Rails engine anymore in that case or we have to have a conditional parent class which probably is fine.

**Comment by excid3** [comment]
@kylekeesling want to give the [handle-actioncable-missing branch](/excid3/noticed/tree/handle-actioncable-missing) a try?

**Comment by kylekeesling** [comment]
This seems to have done the trick! I removed the boilerplate `channels/application_cable/channel.rb` class and I can still get the app to boot up.

Thanks for your work on this!

**Comment by excid3** [comment]
Great! I will merge that and create a new release. 👍
