### ISSUE TITLE
Rails crashes when not using ActionCable on 2.0.2 and above.

### ISSUE THREAD

**Issue by btwelch-corp** [excid3/noticed#392]
## Bug Report

**Describe the Bug:**
In rails 7, while not using action_cable as a dependency, when upgrading from 2.0.0 to 2.0.6, I'm getting:

NameError: uninitialized constant ApplicationCable (NameError)
  class NotificationChannel < ::ApplicationCable::Channel

... when running `rails s` or migrations.

**To Reproduce:**
Remove action_cable as dependency in rails project.

1. Remove action_cable as dependency in rails project
2. Update gemfile to use Noticed 2.0.2 or higher
3. Run `rails s` 

**Expected Behavior:**
The app should run without error.

**Actual Behavior:**
I get the error:
NameError: uninitialized constant ApplicationCable (NameError)
  class NotificationChannel < ::ApplicationCable::Channel

**Screenshots (if applicable):**
n/a

**Environment:**
- Noticed gem version: 2.0.2 (or above)
- Ruby version: 3.3.0
- Rails version: 7.1.2
- Operating System: OSX, Sonoma, M1

**Additional Context:**
Everything works fine on 2.0.1

**Possible Fix:**
n/a

**Steps to Reproduce with Fix (if available):**
n/a

**Related Issues:**
n/a

**Labels to Apply:**
n/a

**Checklist:**
- [x] I have searched for similar issues and couldn't find any
- [x] I have checked the documentation for relevant information
- [x] I have included all the required information

**Comment by excid3** [comment]
Please provide the full stacktrace.

**Comment by stephannv** [comment]
This happens because you project doesn't have a ApplicationCable::Channel class, you must create it:
```ruby
# app/channels/application_cable/channel.rb
module ApplicationCable
  class Channel < ActionCable::Channel::Base
  end
end
```

@excid3 I'm not sure the best solution here, but this works:
```ruby
# app/channels/noticed/notification_channel.rb
module Noticed
  class NotificationChannel < Object.const_defined?("ApplicationCable::Channel") ? ::ApplicationCable::Channel : ActionCable::Channel::Base
    def subscribed
      stream_for current_user
    end

    def unsubscribed
      stop_all_streams
    end

    def mark_as_seen(data)
      current_user.notifications.where(id: data["ids"]).mark_as_seen
    end

    def mark_as_read(data)
      current_user.notifications.where(id: data["ids"]).mark_as_read
    end
  end
end
```

**Comment by excid3** [comment]
Right, but creating an app with ActionCable did not fail so I need complete reproduction steps. Maybe enabling eager loading would reproduce it.

**Comment by stephannv** [comment]
> Right, but creating an app without ActionCable did not fail so I need complete reproduction steps. Maybe enabling eager loading would reproduce it.

Yeah @excid3, on my fresh new app, I could not reproduce this error, I can start the app (rails console & server and run tests) and I can send notifications with no problems. But on my job app (very old rails app), it couldn't start it (console, server or tests), the error reported happens. 
But on my fresh new app if I run `Noticed::NotificationChannel` on console, the error is raised:
```
❯ rails c
Loading development environment (Rails 7.1.3)
irb(main):001> Noticed::NotificationChannel
/Users/stephann/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/noticed-2.1.0/app/channels/noticed/notification_channel.rb:4:in `<module:Noticed>': uninitialized constant ApplicationCable (NameError)

  class NotificationChannel < ::ApplicationCable::Channel
                              ^^^^^^^^^^^^^^^^^^
Did you mean?  ApplicationJob
               ApplicationMailer
               ApplicationPage
irb(main):002>
```

**Comment by excid3** [comment]
Confirmed `eager_load = true` reproduces it.
