### ISSUE TITLE
[BUG] Forbidden nil access when using action_cable default channel

### ISSUE THREAD

**Issue by mochetts** [excid3/noticed#432]
## Bug Report

**Describe the Bug:**
Error when setting action cable delivery method with default channel.

**To Reproduce:**
Add this to your `ApplicationNotifier`

```rb
deliver_by :action_cable do |config|
  config.message = -> { {reload: true} }
end
```

Note the missing `channel` config. This should use the default channel included `Noticed::NotificationChannel` in the gem as [seen here](https://github.com/excid3/noticed/blob/main/lib/noticed/delivery_methods/action_cable.rb#L7).

Then send any notification.

**Expected Behavior:**
No errors should occur

**Actual Behavior:**
Error occurs

**Screenshots (if applicable):**
![Screenshot 2024-03-26 at 3 20 22 PM](https://github.com/excid3/noticed/assets/3678598/b969a651-1e71-434f-a19c-e1c711f0531f)

**Environment:**
- Noticed gem version: 2.2.1
- Ruby version: 3.2.2
- Rails version: 7.1.2
- Operating System: macOS Sonoma 14.4

**Additional Context:**
It seems that when doing `fetch_constant` passing in the `:channel` symbol it doesn't find the key in the `config` hash, therefore generating a forbidden `nil` access.

**Possible Fix:**
n/a

**Steps to Reproduce with Fix (if available):**
n/a

**Related Issues:**
n/a

**Labels to Apply:**
n/a

**Checklist:**

- [x] I have searched for similar issues and couldn't find any
- [x] I have checked the documentation for relevant information
- [x] I have included all the required information

**Comment by excid3** [comment]
Thanks @mochetts. Will get that fixed. 👍

**Comment by excid3** [comment]
It seems like your error is happening inside OrderedOptions which would mean the key it's looking up is `nil`, not `:channel` which is odd. 🤔

**Comment by mochetts** [comment]
@excid3 yep... maybe because I'm not defining `channel` in the config?

**Comment by excid3** [comment]
I don't think so because we `fetch_constant(:channel)` which would be the key. Will try and reproduce out outside the test suite.

**Comment by mochetts** [comment]
It seems that I'm running an older version of the gem. This is the code I have:
```rb
    # delivery_method.rb

    def fetch_constant(name)
      option = config[name]
      option.is_a?(String) ? option.constantize : evaluate_option(option)
    end
```

That `option = config[name]` is now `option = evaluate_option(name)`

**Comment by mochetts** [comment]
I'll pull 2.2.2 and see if it still replicates

**Comment by excid3** [comment]
Ah yeah, that may have been fixed already then.

`option` would end up nil because `:channel` wasn't in the config, so `evaluate_option(nil)` would have been called.

**Comment by mochetts** [comment]
I was runnning 2.2.1. Seems to be working on 2.2.2. Had some issues upgrading the gem with `bundle update` tho. It upgraded a whole bunch of things that made my puma to crash.

**Comment by excid3** [comment]
You can `bundle update noticed` to only update one dependency. 👍

**Comment by mochetts** [comment]
Yep, that's what I did

**Comment by excid3** [comment]
Strange, it shouldn't I don't think!

**Comment by excid3** [comment]
Btw, just pushed up some additional tests to confirm the default channel and stream work. 👍

**Comment by mochetts** [comment]
I had to do:
```
bundle update --conservative noticed
```

**Comment by excid3** [comment]
I always forget about that flag. Makes sense!
