### ISSUE TITLE
[BUG] NoMethodError .to_notifier

### ISSUE THREAD

**Issue by falegk** [excid3/noticed#437]
## Bug Report

**Describe the Bug:**
After upgrading to 2.2.2 (from 1.6.2) I tried to use the `notification.to_notifier` (it exists in the documentation) but I'm getting NoMethodError. I used to use the .to_notification in the previous version.
I checked the noticed code a little and I think this method is not implemented in version 2.

**To Reproduce:**
```
notification = user.notifications.first
notification.to_notifier
# Or just
Noticed::Notification.first.to_notifier
```

**Expected Behavior:**
Deserialize the object and return the Noticed notifier object.

**Actual Behavior:**
`method_missing': undefined method to_notifier' for #<ScanEventNotifier::Notification>`

**Environment:**
- Noticed gem version: 2.2.2
- Ruby version: 3.1.4
- Rails version: 6.1.7.7
- Operating System: Docker ruby:3.1.4-slim-bullseye

**Possible Fix:**
Based on the old code
```
   def to_notification
      @_notification ||= begin
        instance = type.constantize.with(params)
        instance.record = self
        instance.recipient = recipient
        instance
      end
    end
```

we can have something similar (I didnt test it)
```
# /main/app/models/noticed/notification.rb
  def to_notifier
    _event = event
    instance = _event.type.constantize.with(params)
    instance.record = _event.record
    instance
  end
```

**Checklist:**

- [X] I have searched for similar issues and couldn't find any
- [X] I have checked the documentation for relevant information
- [X] I have included all the required information

**Comment by excid3** [comment]
Thanks for the heads up. This was removed.

We use single table inheritance now, so the notifications from the database automatically the correct class instead of having to be converted.
