### ISSUE TITLE
Querying notifications for associations

### ISSUE THREAD

**Issue by benwalks** [excid3/noticed#45]
First, thanks for the great gem!

This is not a bug report, but a question that I was hoping you could help with.

I have a Document model that `has_many` comments, each of which can have an associated notification for a particular user as the recipient.

I want to be able to mark all of a document's comment notifications as read when a user opens a document but I'm finding it difficult to query the notification's JSONB params based on the association data.

An alternative method would be to attach comment notifications to the parent Document, rather than creating notifications per comments, but I can't help but feel that there's a simple method to query an associations' notifications that I just can't wrap my head around.

Thanks again.

**Comment by excid3** [comment]
Details on querying notifications are laid out at the bottom of the readme. 👍

https://github.com/excid3/noticed#associating-notifications

**Comment by benwalks** [comment]
Thanks for the quick response. Maybe I should re-phrase my question:

Can I query Noticed notification params on anything other than the `Noticed::Coder.dum(self).to_json` query on the model that was added to the params?

For example, if the params of a notification includes a 'comment' which has a `document_id`, can I query for notifications based on that attribute of the comment param?

**Comment by excid3** [comment]
You can query against any of the data stored in the json column, or the association if you add that.

For your example, I would include the comment and the document in the notification params so you can query either one.

**Comment by benwalks** [comment]
Great idea, thanks. I'll have to read up on JSONB queries!
