### ISSUE TITLE
[BUG] Events created in nested transactions can fail to deliver 

### ISSUE THREAD

**Issue by ryanshellberg** [excid3/noticed#452]
## Bug Report

**Describe the Bug:**
Originally called out as a concern in the [V2 PR](https://github.com/excid3/noticed/pull/313#discussion_r1452563955). When an event is created inside of a transaction, the corresponding `EventJob` fires before the event itself is created. This leads to a DeserializationError which is then discarded, so the failure was quite tricky to track down.  

**To Reproduce:**
A little tricky to reproduce here because it is a race condition, but our code looks like this:

```
Person.transaction do 
  ... other changes ...
  ReportComplete.with(report: report).deliver(report.user)
end
```

**Expected Behavior:**
EventJob's are created after the event is committed to the database. 

**Actual Behavior:**
EventJob's are fired off before the event is committed to the database. 

**Environment:**
- Noticed gem version: 2.3.1
- Ruby version: 3.3.1
- Rails version: 7.1.3.3
- Operating System: OSX 14.5

**Possible Fix:**
Seems like using an after_commit callback to fire the job should work. 

**Related Issues:**
https://github.com/excid3/noticed/pull/313#discussion_r1452563955

**Checklist:**

- [X] I have searched for similar issues and couldn't find any
- [X] I have checked the documentation for relevant information
- [X] I have included all the required information

**Comment by excid3** [comment]
I wouldn't consider this a bug in Noticed. You should deliver the notification after the transaction is completed.

Rails 7.2 is going to help with this by enqueuing after transaction: https://edgeguides.rubyonrails.org/7_2_release_notes.html#prevent-jobs-from-being-scheduled-within-transactions

**Comment by ryanshellberg** [comment]
Good point, thanks for the info on the upcoming Rails change!
