### ISSUE TITLE
[BUG] Documentation FCM delivery method

### ISSUE THREAD

**Issue by deivinsontejeda** [excid3/noticed#456]
## Bug Report

**Describe the Bug:**
I was playing with FCM Delivery method and seeing the [documentation](https://github.com/excid3/noticed/blob/main/docs/delivery_methods/fcm.md) made mention to [`cleanup_device_token` ](https://github.com/excid3/noticed/blob/main/docs/delivery_methods/fcm.md#handling-failures) but exploring the specs you need to define [config.invalid_token](https://github.com/excid3/noticed/blob/main/test/delivery_methods/fcm_test.rb#L62C7-L62C20) block. 

I possible made a mistake reporting this as bug, excuse me in advantage, just don't want to leave this off

**To Reproduce:**

1. Create a simple Echo notifier
```ruby
class MobileEchoNotifier < ApplicationNotifier
  deliver_by :fcm do |config|
    config.credentials = Rails.root.join('config/certs/fcm.json')
    config.device_tokens = -> { recipient.notification_tokens.pluck(:token) }
    config.json = lambda { |device_token|
      {
        message: {
          token: device_token,
          notification: {
            title: "Test Title #{Time.current.strftime('%Y-%m-%d %H:%M:%S')}",
            body: 'Test body'
          }
        }
      }
    }
    config.invalid_token = ->(device_token) { pp device_token } # <= Invalid token is yielded
  end
end
```

**Comment by excid3** [comment]
Send a PR 👍
