### ISSUE TITLE
[BUG] FCM claims to support `Symbol` for credentials

### ISSUE THREAD

**Issue by bvogel** [excid3/noticed#475]
## Bug Report

**Describe the Bug:**
FCM does not support configurations through symbols any more.

**To Reproduce:**
```
    deliver_by :fcm do |config|
      config.credentials = :firebase_credentials
      config.device_tokens = :fcm_device_tokens
      config.json = :firebase_notification
    end
```
should work, but results in `ArgumentError: FCM credentials must be a Hash, String, Pathname, or Symbol` as https://github.com/excid3/noticed/commit/47b032d8f2a7d7e677d4bea removed symbol support. 

**Expected Behavior:**
Symbols should work or error and documentation should reflect the cuent state.

**Actual Behavior:**
ArgumentError: FCM credentials must be a Hash, String, Pathname, or Symbol

**Environment:**
- Noticed gem version: 2.2.2 
- Ruby version: 3.3.4
- Rails version: 7.1.3.4
- Operating System: docker

**Possible Fix:**
add this back in:
```
          when Symbol
            notification.send(option)
```

**Checklist:**

- [x] I have searched for similar issues and couldn't find any
- [x] I have checked the documentation for relevant information
- [x] I have included all the required information

**Comment by excid3** [comment]
`evaluate_option` is what handles the Symbol, so it works as expected. 

The return value of your function needs to return a hash of credentials, or a path to the credentials file.

**Comment by bvogel** [comment]
ok, for anyone else running into this: make sure the method defined by the symbol is public
