### ISSUE TITLE
NameError (uninitialized constant CommentNotification)

### ISSUE THREAD

**Issue by londonbridges13** [excid3/noticed#48]
Cool Gem!

I keep getting this error in the terminal when I run:
irb(main):002:0> notification = CommentNotification.with(comment: @comment)

I don't know what I'm missing

**Comment by excid3** [comment]
You haven't provided any details like the stacktrace or your code, so there's nothing I can do to help.

Send me more information and I'll take a look.

**Comment by londonbridges13** [comment]
😅  

<img width="615" alt="Screen Shot 2020-09-23 at 9 14 04 AM" src="https://user-images.githubusercontent.com/11670379/94024525-2616f700-fd7d-11ea-9be6-bc6c197502bc.png">

<img width="989" alt="Screen Shot 2020-09-23 at 9 12 30 AM" src="https://user-images.githubusercontent.com/11670379/94024361-ef40e100-fd7c-11ea-8d12-bd32b4830899.png">

**Comment by excid3** [comment]
Lines 3 and 4 in your code are trying to access a class that isn't defined until a couple lines later. Comment those out. They're examples to use in other parts of your app.

**Comment by londonbridges13** [comment]
Thanks that was it!
