### ISSUE TITLE
ArgumentError (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true)

### ISSUE THREAD

**Issue by RSeven** [excid3/noticed#49]
Trying to use url helpers to get the full url inside a Notification returns an error because, apparently, default_url_options is not defined inside a Notification object.
  
 ```
 def url
    video_show_url(slug: params[:video].slug)
  end
```
![image](https://user-images.githubusercontent.com/502389/94615211-bffb0a00-027d-11eb-9e49-1c1c74a2ec7c.png)

I fixed this by adding the following code inside my NewVideoNotification class.
```
private
  def default_url_options
    Rails.application.config.default_url_options
  end
```

Maybe this could be added to Noticed::Base.

**Comment by cabourn** [comment]
I may be wrong, but I've also been trying to fix this today. Personally I set the host option in the relevant environment files.

#### **`config/environments/development.rb`**
```
Rails.application.routes.default_url_options[:host] = 'localhost:3000'
```

**Comment by andrewhttr** [comment]
I to had to set the default host to fix this.

**Comment by cabourn** [comment]
If that's the best solution, maybe just the docs can be updated under 'URL Helpers' to include the configuration?

**Comment by RSeven** [comment]
I already have that setting, but it is slightly different, maybe that's it. This setting works for everything else, though, it just seems invisible inside a Notification class.

**config/environments/development.rb**
```
Rails.application.configure do
  config.default_url_options = { :host => 'localhost:3000', :protocol => 'http://', :locale => nil }
end
```
> I may be wrong, but I've also been trying to "fix" this today. Personally I set the host option in the relevant environment files.
> 
> #### **`config/environments/development.rb`**
> ```
> Rails.application.routes.default_url_options[:host] = 'localhost:3000'
> ```

**Comment by RSeven** [comment]
Yeap, that solves it!

**config/environments/development.rb**
```
Rails.application.configure do
  routes.default_url_options[:host] = 'localhost:3000'
end
```
Don't really get the difference between this and my previous setting.

**Comment by excid3** [comment]
If you're going to try and access URLs in the console or in mailers, Rails requires you to set the default url options since it doesn't have a request to use the url from. Just standard Rails things, nothing specific to Noticed.

Definitely a point of confusion since it's not very clear in Rails: https://github.com/rails/rails/issues/29992

We can add a note to the readme though so people don't forget.

**Comment by nikolaz90** [comment]
Thanks for this!
solved problem!
Rails.application.configure do
  routes.default_url_options[:host] = 'localhost:3000'
end

**Comment by Dujota** [comment]
small side note, if you do the config changes, make sure to restart the server. Dealt with this issue and accepted solution seemed to not work, but restarting server after config did the trick. In case anyone ran into problem but didnt fix.

**Comment by talhajunaid63** [comment]
I added the following in my config file, it is working fine locally but on staging/production its still throwing this error: 

```
ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
```

my config file looks like this:

```
  Rails.application.routes.default_url_options[:host] = ENV['HOST_DOMAIN']
```

```
config.action_mailer.default_url_options = {
    host: ENV['HOST_DOMAIN'], protocol: 'https'
  }
```

anyone else still facing this issue?

**Comment by rsdsllc-com-ryanc** [comment]
> I added the routes.default_url_options config in my config file, It is working fine locally but on staging/production its still throwing this error:
> 
> ```
> ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
> ```
> 
> my config file looks like this:
> 
> ```
>   Rails.application.routes.default_url_options[:host] = ENV['HOST_DOMAIN']
> ```
> 
> ```
> config.action_mailer.default_url_options = {
>     host: ENV['HOST_DOMAIN'], protocol: 'https'
>   }
> ```
> 
> anyone else still facing this issue?

YES, this is exactly what is happening to me. All of my mailers throw this error of a missing host but I have mine configs same as you. 

When I put logs at the top of the mailer classes to check the default_url_options they show up. However, in the actual method that is called on the mailer when its time to execute, in that method the default_url_options show up nil. 

I can't find a solution for why the default_url_options are all of a sudden nil in production after showing them being set correctly on load.
