### ISSUE TITLE
Checking if notification is read before sending email/text

### ISSUE THREAD

**Issue by ykamin-booth** [excid3/noticed#50]
Hi, I'm not sure if there is a better way to do this, but I wanted to see if there is a standard way to delay the deliver_by email/twilio methods and check if the notification is read off the database before sending. Right now, I have it built into my conditional check in the delivery method.
```
deliver_by :email, mailer: "UserMailer", method: :message_notification, if: :email_notifications?

def email_notifications?
  sleep(60)
  record.reload
  if record.read?
    return false
  else
...
```

**Comment by excid3** [comment]
Delivery methods are all sent at the same time, so I don't think this would work how you want anyways.

I've been meaning to add a delay option to delivery methods so they could be run later, such as writing to the db immediately and emailing the user after 5 minutes.

**Comment by ykamin-booth** [comment]
From my testing it seems to be working. The db notification is showing up immediately and if I mark it as read within a minute based on my sleep time, the email isn't sending--otherwise it is.

**Comment by ykamin-booth** [comment]
Actually this is causing a separate issue. Even though I am sending the notification with deliver_later, waiting in the second process is preventing anything else from happening in my posts controller. Not sure if I need to use active job or something else to stop that from happening.

**Comment by excid3** [comment]
You should almost always deliver later in background jobs.
