### ISSUE TITLE
Get response from delivery method in callback

### ISSUE THREAD

**Issue by dwightwatson** [excid3/noticed#53]
I wonder if it's currently possible, or whether it would be a useful feature to be able to access the delivery response in an after callback.

```rb
class InvitationNotification < ApplicationNotification
  deliver_by :vonage

  after_vonage :record_vonage

  # ...

  private 

  def record_vonage
    recipient.deliveries.create(status: vonage_response)
  end
end
```

This is a contrived example (using `vonage_response`, which would be the status code from [this line](https://github.com/excid3/noticed/blob/master/lib/noticed/delivery_methods/vonage.rb#L6). This would provide the flexibility to actually record whether a delivery method was successful or not.

My specific use-case is being able to determine whether text messages where delivered or not as they're displayed back to a user, though I'm sure it would be equally beneficial for most delivery methods if you needed logging/tracking of the response.

**Comment by excid3** [comment]
We don't have any delivery tracking other than if a job succeeds or fails, but I could see that being useful to record the results. 👍 

I guess we would need to record each delivery in a json column or something with the status (success or fail) and the timestamp?

**Comment by dwightwatson** [comment]
I'm not sure it's worth recording that in the database for each delivery method, especially if you don't care for the result and now your table is filling up with data you don't need. I was thinking more that it would be available immediately in the callback in case you wanted to do some handling with it, otherwise it's lost. But I'm not sure if `ActionModel::Callbacks` would allow you to provide that context/response in the callback method.

**Comment by excid3** [comment]
Since everything delivers in jobs, I'm not sure there's any way to safely store it other than the database.

**Comment by rbague** [comment]
I agree with @excid3 that there is not a safe way to store it other than a database. But you can accomplish something similar to what you mean, by changing the `after` callback to an `around` callback. By using the `around` callback, you can store the result of the delivery in a variable, and then process it any way you want.

```ruby
class InvitationNotification < ApplicationNotification
  deliver_by :vonage

  around_vonage :record_vonage

  # ...

  private 

  def record_vonage(&deliver)
    vonage_response = deliver.call # returns an HTTP::Response instance
    recipient.deliveries.create(status: vonage_response) # or vonage_response.parse.dig("messages", 0, "status")
  end
end
```
With this, the only change that the libray needs is to return the HTTP reponse in the [vonage delivery](https://github.com/excid3/noticed/blob/master/lib/noticed/delivery_methods/vonage.rb#L4).
All the other delivery methods already return the HTTP response, or the result of the delivery (e.g. the databAse delivery returns the created record)
```ruby
module Noticed
  module DeliveryMethods
    class Vonage < Base
      def deliver
        response = post("https://rest.nexmo.com/sms/json", json: format)
        # ...

        response # return the response so it is available in the `around_vonage` callback
      end

      # ...
    end
  end
end
```

**Comment by excid3** [comment]
@rbague that works nicely. 👍

We can update the delivery methods to have better return values. Potentially we could standardize it so they are expected to return a hash with metadata about the delivery:

```ruby
{
  success: true,
  response: response,
}
```

That does bring up the question if we still want to raise an error if a delivery method fails. The main reason we raise an error right now is that it will trigger a retry of the delivery in ActiveJob which is useful.

**Comment by rbague** [comment]
I think raising an exception is a really useful feature to have, as it allows you to write your custom retry logic using the [parent_class](https://github.com/excid3/noticed/blob/7e8b859d02ad8fd15b658751cea37a7fcb6e4b5a/lib/noticed.rb#L34) configuration.
But yes, I agree with you that in the end, it will make more sense if all the delivery methods return an standardized response, instead of each of them returning a different value
