### ISSUE TITLE
Record HTTP requests for testing

### ISSUE THREAD

**Issue by rbague** [excid3/noticed#60]
Whilst working on #59 I noticed that the `Vonage`, `Slack`, `Twilio` and `MicrosoftTeams` tests trigger a real HTTP request to different services, which always fail and raise a `Noticed::ResponseUnsuccessful` exception, making all of those tests a little bit more complicated to read and write.

It may be great if we could locally record successful requests to each service, and use them in the tests, so we could replicate real case scenarios. I've used [WebMock](https://github.com/bblimke/webmock) in the past for this specific case and it works great.

**Comment by excid3** [comment]
Yes! It's been on my todo list but forgot about it. I was more worried about getting the notifications sent when I was first building this.

WebMock would be great.

**Comment by rbague** [comment]
I can help setting up WebMock and stub the slack request, but I don't have a paid account for Twilio or Vonage so I can't record those requests.

I'll try and send a PR in the next couple days 😄

**Comment by excid3** [comment]
That would be fantastic. 👍 

I was just using their trial accounts to test so far with Vonage and Twilio. 😅
