### ISSUE TITLE
`mark_as_unread!` does not work for association collections

### ISSUE THREAD

**Issue by elvinaspredkelis** [excid3/noticed#66]
Hey!

This gem is a blessing and saved so much time already. I ran into this obscure use case where I'd need to mark a bunch of notifications as unread and the gem doesn't seem to support it (yet). 🤷‍♂️

Gem version: **1.2.19**

### Expected Behavior
Running `user.notifications.mark_as_unread!` should mark the notification records as not read.

### Actual Behavior
Running `user.notifications.mark_as_unread!` throws an `undefined method 'mark_as_unread!' for #<Notification::ActiveRecord_Associations_CollectionProxy:0x0000000000000>` error.

### Additional Information

- Running `user.notifications.mark_as_read!` works as one would expect.
- Documenting association methods would be a great add as well! 📚

**Comment by excid3** [comment]
I think this is a bug. The concern should define `class_methods do` and not `module ClassMethods` so that method is available.

**Comment by excid3** [comment]
Actually, seems to work without it. Added a test to confirm it was broken, but it passed. 

Must be because the module name matches what Concern looks for.

**Comment by elvinaspredkelis** [comment]
Indeed. Perhaps it makes sense to add a corresponding method there to mark multiple notifications unread too?

**Comment by excid3** [comment]
Like I mentioned, it's already there and has been for a while. https://github.com/excid3/noticed/blob/master/lib/noticed/model.rb#L18-L20

Here's the test I just added to confirm it works: https://github.com/excid3/noticed/commit/8f9d0707282a98f19f6d1f194a732445570f717a

Your model includes the Noticed::Model module?

**Comment by elvinaspredkelis** [comment]
Haha, yep, like I stated in the "Additional Information", mark_as_read! does work as expected. 

The opposite function mark_as_**un**read! does not exist, however.

**Comment by excid3** [comment]
Ah! I read through too quickly. 😅

I blame it being Monday. I'll get that fixed shortly.

**Comment by elvinaspredkelis** [comment]
Perfect, thank you! 👏

I suppose documenting methods for collections would be sweet as well. Might help out people who wouldn't test their luck out.

**Comment by ykamin-booth** [comment]
Hey, it seems that the mark_as_read! and mark_as_unread! methods no longer work for the association collections as of V2 with the new models. Is this intentional?

**Comment by chrisortman** [comment]
@ykamin-booth is your association empty when you call it and get the error?
