### ISSUE TITLE
NameError? Uninitialized constant ApplicationJob

### ISSUE THREAD

**Issue by christopheragnus** [excid3/noticed#68]
Hi there,

I have run the setup for Noticed. When I try to deliver an notification, a NameError occurs.
To replicate the bug;
```

1. bundle add "noticed"
2. rails generate noticed:model
3. rails generated noticed: notification CommentNotification & uncomment deliver_to database
4. Send notification to a user.  notification = CommentNotification.with(comment: @comment) 
5. Delivery notification immediate: notification.deliver(@comment.post.author)
6. An NameError occurs.
```

I am running Rails 6.

**Comment by excid3** [comment]
Noticed currently expects your app to have the default Rails `ApplicationJob` class. The error `Uninitialized constant ApplicationJob` says you've removed it from your app. 

You'll want to add ApplicationJob back to your app or use `Noticed.parent_class = "ActiveJob::Base"` to specify a different job class.
