### ISSUE TITLE
Sidekiq 

### ISSUE THREAD

**Issue by kb1995** [excid3/noticed#74]
Hello,

I am using Sidekiq and I am encountering this error https://github.com/mperham/sidekiq/wiki/FAQ#why-am-i-seeing-a-lot-of-cant-find-modelname-with-id12345-errors-with-sidekiq in production which causes errors like "Error while trying to deserialize arguments: Couldn't find Notification with 'id'=24736"

Any advice on how I could prevent this from happening for my noticed jobs?

**Comment by excid3** [comment]
It's not anything to do with Sidekiq actually. It's ActiveJob deserializing arguments with GlobalID. 

This should only happen if a record was deleted before a Notification was delivered. We could probably add a `rescue_from ActiveRecord::RecordNotFound` to the jobs so we can safely ignore those.

**Comment by silva96** [comment]
see #77
