### ISSUE TITLE
Handle deserialization error for deliver_by email when record destroyed

### ISSUE THREAD

**Issue by silva96** [excid3/noticed#77]
Probably would be nice to have an explanation in the readme like this:

```ruby
class NotificationMailer < ApplicationMailer
  rescue_from(ActiveJob::DeserializationError) do |e|
    Rails.logger.info("Skipping notification due to #{e.message}")
  end

  def some_notification
    # ... params[:some_record] that can be destroyed, will raise ActiveJob::DeserializationError, so we catch it.
  end
```

**Comment by silva96** [comment]
doesn't work because ActionMailer does not implement ActionJob::Rescueable

https://github.com/rails/rails/issues/19793

Any workaround?

**Comment by silva96** [comment]
Actually, de Noticed::DeliveryMethods::Email job  is failing, not the mailer itself

How do you suggest to inject the 

```ruby
rescue_from(ActiveJob::DeserializationError) do |e|
    Rails.logger.info("Skipping notification due to #{e.message}")
  end
  ```
  
  here?
  
```ruby
module Noticed
  module DeliveryMethods
    class Email < Base
      option :mailer

      def deliver
        mailer.with(format).send(method.to_sym).deliver_now
      end

      private

      def mailer
        options.fetch(:mailer).constantize
      end

      def method
        options[:method] || notification.class.name.underscore
      end

      def format
        params = if (method = options[:format])
          notification.send(method)
        else
          notification.params
        end
        params.merge(recipient: recipient, record: record)
      end
    end
  end
end
```

**Comment by silva96** [comment]
I'm in a rabbit-hole Chris, any ideas?

**Comment by silva96** [comment]
I ended up discarding it in ApplicationJob

![image](https://user-images.githubusercontent.com/4019924/102841517-d976a280-43e3-11eb-87bf-5a9551079f60.png)

**Comment by excid3** [comment]
I like the `discard_on` solution. It makes sense that we'd want to do that if we can't safely deserialize everything. 

Maybe this should just be added to our jobs by default?

**Comment by silva96** [comment]
I don't know, putting this on the readme works fine for me.

**Comment by tbcooney** [comment]
> Just a note: this error is more likely (IMO) to happen if you are enqueuing a Notification _inside_ of a database transaction. If the job is enqueued and picked up _before_ the transaction is committed, the Notification record can't be read by the enqueued notification job and thus throws this error.
> 
> In these cases, you very likely _do not_ want to discard the job, as if the job simply retries once or twice, the transaction will likely have been committed and the job will succeed. In general, you want to try to ensure that you are not enqueuing notifications while inside of a database transaction. Aside from that, you want to allow these errors to go into the retry flow, and only if they fail continuously would I presume that the Notification record was intentionally deleted.

I'm having this issue with Action Text, and Notifications. Notifications are sent out when a User is mentioned in a comment. We use Trix and ActionText to handle the at-mentions, and Action Text needs to enqueue an analyze job after the comment is created. The delivery methods have a 50% chance of performing before the Action Text analyze job is completed and will end up discarding the delivery method due to a ActiveJob::DeserializationError.

**Comment by fractaledmind** [comment]
@tbcooney: Can you share how you are enqueuing the notifications currently?

**Comment by tbcooney** [comment]
> @tbcooney: Can you share how you are enqueuing the notifications currently?

We enqueued the notifications via a callback on the Note model.

For example,
```
class Note < ApplicationRecord
  include ActionView::RecordIdentifier

  has_rich_text :content
  after_create :notify_mentioned_members
end
```

We probably should've been using `after_create_commit` rather than a `after_create` callback to ensure that transaction for both the Note and the ActionText::RichText were completed.

**Comment by fractaledmind** [comment]
Indeed. It always needs to be some form of `after_commit`.

**Comment by joemasilotti** [comment]
I was just [bit by this on my app](https://github.com/joemasilotti/railsdevs.com/issues/211) and had a bunch of email notifications silently failing. Is this "common knowledge" for the gem, or job enqueuing in general? If not, I'd love to add some documentation so this doesn't happen to anyone else.

**Comment by tbcooney** [comment]
> I was just [bit by this on my app](https://github.com/joemasilotti/railsdevs.com/issues/211) and had a bunch of email notifications silently failing. Is this "common knowledge" for the gem, or job enqueuing in general? If not, I'd love to add some documentation so this doesn't happen to anyone else.

Add it as a best practise!

The Rails guides explain that `after_commit` is the only callback that is triggered once the database transaction is committed. I have a propensity to _not read_ and these errors are frustrating to track down. But, it's well documented online that without an `after_commit` callback, you may see strange errors in Sidekiq to the tune of `Cannot find ActionText::Attachment with ID=12345`. 

I've found this to be a best practise when using Rails callbacks (just to be clear, the best practise being the preference of `after_commit` to `after_create`.

**Comment by joemasilotti** [comment]
Good to know, thanks @tbcooney! I'll open a PR with a new section to the README.

**Comment by excid3** [comment]
Yes, that would be great to add to the readme. 👍

**Comment by joemasilotti** [comment]
PR opened! #189
