### ISSUE TITLE
Bug: delay: 5.minutes, unless: :read? shows undefined method read?

### ISSUE THREAD

**Issue by sjieg** [excid3/noticed#78]
Hello, first of all, cool stuff with this gem. I just moved away from Activity Notifications (a does-it-all gem) to this one, because in the end an all inclusive gem never does exactly what you want.

So, maybe I'm doing something wrong, but I'm following what's explained here: https://github.com/excid3/noticed#fallback-notifications.

This gives me an error:

```Bash
NoMethodError - undefined method `read?' for #<ReportNotification:0x000000001cf7bdd8>
```

Or what ActiveJob / Sidekiq is throwing:

```Bash
[ActiveJob] [NotifyAboutReportJob] [8f6b2ac5-0dde-4c8e-8d8c-6cb8f64c1bb5] [Noticed::DeliveryMethods::Email] [c340b4f2-bdee-44a0-a1cc-7e45b3452304] Error performing Noticed::DeliveryMethods::Email (Job ID: c340b4f2-bdee-44a0-a1cc-7e45b3452304) from Sidekiq(default) in 5.94ms: NoMethodError (undefined method `read?' for #<ReportNotification:0x000000001cf7bdd8>
```

Trying to debug this a little bit, it seems like the notification class isn't inheriting the functions of its parent:

```Ruby
class ReportNotification < Noticed::Base
  deliver_by :database
  deliver_by :email, mailer: "UserMailer", method: :report_summary, format: :format_for_email, delay: 5.seconds, unless: :is_read
  param :report

  def is_read
    pp self # <-- prints okay
    pp self.read_at # <-- throws error undefined method
    pp self.read? # <-- undefined method
    self.read?
  end
end
```

The weird thing is that printing `self` does show `read_at` as an attribute:

```
#<ReportNotification:0x000000001f3fd260
 @params=
  {:report=>
    #<Report:0x000000001f3ac478 [...]>},
 @recipient=
  #<User [...]>,
 @record=
  #<Notification:0x000000001f3eeeb8
   id: 15,
   recipient_type: "User",
   recipient_id: 2,
   type: "ReportNotification",
    {:report=>
      #<Report:0x000000001f470468>},
   read_at: nil,
   created_at: Mon, 28 Dec 2020 11:02:45 UTC +00:00,
   updated_at: Mon, 28 Dec 2020 11:02:45 UTC +00:00>>
```

While writing this I see I can solve the issue by doing:

```Ruby
def is_read?
  self.record.read?
end
```

But that's not in line with the documentation.

Possibly I have a use case that's not tested:

1. Trigger an Active Job to find all users to be notified
2. Trigger the ReportNotification.deliver_later from there
3. Delay sending an email unless the notification is read withing 5 minutes.

Anyway, what do you think? Let me know if you need more (structured) details.

**Comment by excid3** [comment]
In the latest version, we delegate read? and unread? to the record. 

https://github.com/excid3/noticed/blob/master/lib/noticed/base.rb#L15

Are you on the latest version?

**Comment by sjieg** [comment]
```
Fetching noticed 1.2.21 (was 1.2.20)
Installing noticed 1.2.21 (was 1.2.20)
```
Retested an worked successfully. My bad :)

There still seems to be some other issue with delaying and SideKiq, but I'll investigate that more tomorrow and get back with a new ticket if I have something reproducible,
