### ISSUE TITLE
Send to multiple recipients

### ISSUE THREAD

**Issue by excid3** [excid3/noticed#8]
Allow passing multiple users into `deliver` and `deliver_later`. We can loop through each of them and send notifications for them.

We will need to figure out what to do with callbacks. They could run once for each recipient or for the entire block? Or do we introduce a different interface for sending to multiple?

* [ ] Accepts one or many recipients (use `Array.wrap` to make them consistent)
* [ ] Calls `uniq` on the list of recipients
* [ ] Correctly handle with callbacks

**Comment by weedySeaDragon** [comment]
Will all services _always_ be able to handle a list of recipients? (I don't know if that's a reasonable assumption)
If so, then can you push the responsibility down into the `DeliveryMethod::Base` subclasses? (e.g. always pass them a _collection_ of recipients and let them implement it as needed.
[That doesn't feel right to me, but I honestly don't know if you can assume that]

The `deliver` and `deliver_later` methods "shouldn't care" if they get a single recipient or a list of them -- they should handle either, and then always turn it into a _collection_.

Your questions about running once or running as a block still stands.  And really, you should be able to handle either with some sort of option/config. :-)

JMNSHO

**Comment by kaka-ruto** [comment]
It could help to maintain the same the same interface, esp since they do the same thing and would be easy for our users.

For callbacks, I am trying to think if there's a scenario it can be ran once for the entire block? If so, we can look at how to hit the callback once for the block. Then where it necessitates running a callback once for each recipient, then we can do so. We can look at this on a callback by callback basis

**Comment by excid3** [comment]
@weedySeaDragon Most everything does not understand how to deliver to more than one recipient. We'd be looping through and kicking off delivery jobs for each recipient.

We could introduce a `deliver_multiple` and `deliver_mutiple_later` that accepts multiple recipients, but it feels unnecessary.

**Comment by excid3** [comment]
@kaka-ruto currently the `:deliver` callback is run around the delivery. If we left that alone, it'd fire for every recipient. We could move that around the entire delivery. I feel like the latter is more useful?

**Comment by weedySeaDragon** [comment]
>  **We'd be looping through and kicking off delivery jobs for each recipient.**

So then you'd just loop thru the recipients with the callback OR v.versa.

I think we're all saying the same thing with the `deliver` and `deliver_later` method signatures:  they should be the same whether `recipient:` is a single item or a Collection.  (So you'd handle that in the `perform` method -- turning all single items into a Collection and then dealing with it where you're doing
```
run_callbacks :deliver do
          deliver
end
```

**Comment by kaka-ruto** [comment]
@excid3 yup, `deliver_multiple` and `deliver_mutiple_later` does feel unnecessary.

If the `:deliver` callback can fire once for the entire block and still create a delivery to each recipient, then that'd be awesome. I def feel this is possible

**Comment by excid3** [comment]
Great, that sounds good to me on both items. 👍

**Comment by excid3** [comment]
Alright, shipped as v1.2.1! :shipit:
