### ISSUE TITLE
The gem noticed causes failure on Apple Silicon Ruby on Rails apps.

### ISSUE THREAD

**Issue by MCarroll** [excid3/noticed#81]
Installing of the gem noticed causes, in a jumpstart saas template, on Apple Silicon Ruby on Rails application to throw the following error when running the rails server, and or console commands. 

"gems/http-parser-1.2.2/ext/aarch64-darwin/libhttp-parser-ext.bundle: mach-o, but wrong architecture"

Commenting out:

# gem "noticed", "~> 1.2"

Solve this issue and rails s, c will then run.

**Comment by excid3** [comment]
As you can see in the error, it's the http-parser gem you're having trouble with, not Noticed. 👍 

See: https://github.com/cotag/http-parser/issues/12
