### ISSUE TITLE
uninitialized constant CommentNotification

### ISSUE THREAD

**Issue by fractaledmind** [excid3/noticed#86]
In trying to learn this gem, I created a brand new Rails app and walked thru the installation instructions. However, after having run the generator to get a Notification class, I can't access it from the rails console. You can find my repo here: https://github.com/fractaledmind/noticed-sandbox

And here is the output from my console
```
± bundle exec rails c
Running via Spring preloader in process 87965
Loading development environment (Rails 6.0.3.4)
irb(main):001:0> CommentNotification
Traceback (most recent call last):
        1: from (irb):1
NameError (uninitialized constant CommentNotification)
irb(main):002:0> require_relative 'app/notifications/comment_notification'
=> true
irb(main):003:0> CommentNotification
=> CommentNotification
```

It appears that the `app/notifications/` directory isn't being auto-loaded. But I was under the assumption that everything under `app/` got auto-loaded, so I'm confused.

**Comment by excid3** [comment]
Cloned your repo and it worked fine for me:

```bash
$ bundle
$ yarn
$ rails c
Running via Spring preloader in process 50435
Loading development environment (Rails 6.0.3.4)
irb(main):001:0> CommentNotification
=> CommentNotification
irb(main):002:0>
```
