### ISSUE TITLE
Mobile push notifications? 

### ISSUE THREAD

**Issue by jeremiahlukus** [excid3/noticed#97]
In the video thumbnail it shows a push notification but i don't see anywhere to set this up nor do i anywhere to set app keys for apple devices. Is this gem able to send push notifications to IOS and android devices?

**Comment by excid3** [comment]
That is a Browser notification in Javascript. https://developer.mozilla.org/en-US/docs/Web/API/notification

iOS and Android notifications are a bit more involved as you have to register the device to send to. Looks like this is probably the most popular library for that: https://github.com/rpush/rpush

**Comment by excid3** [comment]
Forgot to mention, would definitely accept a PR for this. I haven't gotten to it quite yet, but I have been meaning to build some Turbo-iOS and Turbo-Android examples so that will come in handy.
