### ISSUE TITLE
Terminology Question/Suggestion

### ISSUE THREAD

**Issue by fractaledmind** [excid3/noticed#98]
First and foremost, I want to say a big thank you for this library. It is awesome and rock-solid and has been seriously useful to my team. When I introduced this to the team, though, there was one point in particular that tripped them up and took some time to clarify: two things are called "Notification".

One of the one hand, you have the `SomeNotification` class that inherits from `Noticed::Base`; on the other hand, you have the `Notification` model which stores the individual database notification records. This terminology confusion is made completely explicit whenever you do something like this when trying to render database notifications in-app: `@notification.to_notification`.

In our team, we have started calling the Noticed classes "Notifiers", so our class names are now `SomeNotifier` and we aliased the `to_notification` method on the `Notification` model to `to_notifier`. This has helped our communication, so I wanted to open the floor for a discussion around the terminology. If you have some alternative terminology you think is better, I'm willing to do the PR either way.

**Comment by excid3** [comment]
I like that! It was definitely something I didn't love but also didn't have a better name for it at the time.

So we'd have basically 3 concepts:
* Notifier (Controls how notifications are sent)
* Notification (notifier saved to the database)
* Delivery Method (a way a notification is delivered)

It'll be a breaking change, but a pretty easy one to find & replace.

**Comment by andrew-newell** [comment]
Just throwing this out there - I've tried adopting this gem over several 20 minute spike sessions and this concept was very difficult to discover the hard way. I definitely like the terminology proposed in #99
